#! /bin/sh

# launch hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# set wallpaper
~/.fehbg &
# start compositor (new backend improves performance)
picom --experimental-backends &
# swap esc and caps lock
setxkbmap -option caps:swapescape
# set compose key
setxkbmap -option compose:ralt

# temp: kill processes about to be relaunched
killall -9 polybar xborders dunst
# launch polybar, notification daemon and compositor addon (round corners)
~/.config/polybar/launch.sh &
/usr/bin/dunst &
~/clone/xborder/xborders --border-alpha 0 &

# load fxitx5 for jp ime
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export GLFW_IM_MODULE=ibus
export SDL_IM_MODULE=fcitx
fcitx5 &

# rename monitors
bspc monitor DP-4 -n left
bspc monitor DP-2 -n center
bspc monitor HDMI-1 -n right

# assign desktops to monitors
bspc monitor left -d 一 二 三
bspc monitor center -d 四 五 六
bspc monitor right -d 七 八 九

bspc config border_width 2
bspc config window_gap 20

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "#33467C"
bspc config focused_border_color "#7AA2F7"
bspc config active_border_color "#33467C"

# application rules
bspc rule -a chromium desktop=I
bspc rule -a firefox desktop=I
bspc rule -a Rofi state=floating border=off
